### ISSUE TITLE
avoid allocations on parseUUID

### ISSUE THREAD

**Issue by vtolstov** [ash3in/uuidv8#10]
What you think to rewrite parseUUID to avoid allocations if used uuid with "-" ?

```go
func parseUUID(uuid string) ([]byte, error) {
	uuid = strings.ReplaceAll(uuid, "-", "")
	if len(uuid) != 32 {
		return nil, errors.New("invalid UUID length")
	}

	return hex.DecodeString(uuid)
}
```

**Comment by ashwingopalsamy** [comment]
Hey, @vtolstov . Appreciate you taking the time to suggest this improvement. It makes the library better for everyone.

Sorry, it took a while for me to respond, as I was out on vacation. This (#12) should probably address your recommendation. Please review.

**Comment by vtolstov** [comment]
thanks
