### ISSUE TITLE
driver.Valuer interface

### ISSUE THREAD

**Issue by vtolstov** [ash3in/uuidv8#11]
does it possible to create interface similar to google/uuid because i need to have uuid type with driver.Valuer to get/set value in db (i can use string, but some tools if i'm specify type string does not automatic convert it to uuid type inside db)

**Comment by ashwingopalsamy** [comment]
Hi again! 👋 Please review #13 and let me know if this would be suffice. 

Anyways, I would love to get reviews for https://github.com/google/uuid/pull/178. Yet to recieve any response from maintainers there, may be folks are on vacation.

**Comment by vtolstov** [comment]
thanks, this works for me

**Comment by vtolstov** [comment]
thanks
