### ISSUE TITLE
lower go requirement

### ISSUE THREAD

**Issue by vtolstov** [ash3in/uuidv8#14]
can you change go requirement from 1.23.x to 1.22.0 , many projects uses 1.22.xx go so i think minimum required go version can be 1.22.0

**Comment by ashwingopalsamy** [comment]
Makes sense! I'll do that.

**Comment by ashwingopalsamy** [comment]
kindly review #15, @vtolstov 👀

**Comment by vtolstov** [comment]
big thanks

**Comment by vtolstov** [comment]
please tag the new version v1.1.2

**Comment by ashwingopalsamy** [comment]
I’ve tagged it as `v1.2.0`.

Would that work for you? Since this is a lightweight niche library with relatively few changes expected across the lifespan, I felt a solid version bump for this release would make sense.

**Comment by vtolstov** [comment]
yeah, thanks, 1.2.0 works fine for me
